# Generated by Django 3.1 on 2020-08-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='area',
            new_name='land_area',
        ),
    ]
