# Generated by Django 3.1 on 2020-08-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_auto_20200827_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='realtors_name',
            new_name='realtor_name',
        ),
    ]
