# Generated by Django 3.1 on 2020-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_auto_20200827_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='realtor_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
