# Generated by Django 3.1 on 2020-08-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_remove_realtor_is_mvc'),
        ('lands', '0006_land_realtor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='land',
            name='realtor_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='realtor_photo',
        ),
        migrations.AddField(
            model_name='land',
            name='realtor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
        ),
    ]
