# Generated by Django 3.1 on 2020-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200822_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
