# Generated by Django 3.1 on 2020-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_mvc',
            field=models.BooleanField(default=False),
        ),
    ]
